jet-lab/jet-governance

- tests/airdrop-staking.ts
This fixes the test failure that prevented the devnet deployment of the latest commit, which was causing people to see panics because they weren't getting the latest bug fixes.
Since votes are based on shares instead of tokens now, the calculation is different and you can get a different number of votes. I calculated the number of votes a user should have after the sequence of events in the anchor tests:
> after "user claims airdrop" adds 4_200_000_000 tokens to user
> 42_000_000_000
> 
> after "user unbonds stake" removes 4_199_999_999 tokens from user
> 10
> 
> after "user cancels unbonding" adds back 4_199_999_999 tokens to user
> 42_000_000_000
> 
> after "user unbonds again" removes 4_199_999_999 tokens from user
> 10
> 
> after "user restakes" adds back 4_199_999_999 tokens to user …
> Fix "mint max votes" test

- app/src/App.less
<details>
<summary>Click to see current mobile button</summary>
</details>
<details>
<summary>Click to see current desktop button</summary>
</details>
<details>
<summary>Click to see updated mobile button</summary>
</details>
<details>
<summary>Click to see updated desktop button</summary>
</details>
> [GVN-345]fix dropdown styling

- app/src/utils/utils.ts
Return `Math.floor(number)` under 100k
> GVN-289 Do not abbreviate number under 100k

- programs/staking/src/lib.rs
add `spl_governance` module to export the declared program id
closes #26
> staking: export internal spl governance program id

- app/src/App.less
<details>
<summary>Click to see current claimed button</summary>
</details>
<details>
<summary>Click to see updated claimed button</summary>
</details>
> [GVN-356] fix claimed button width

- app/src/components/YourInfo.tsx
Changed from
> For each JET token staked, you may cast 1 vote in JetGovern.
to
> Staking JET allows you to cast your vote in JetGovern.
> New staked jet tooltip

- app/src/actions/rescindAndUnstake.ts
- app/src/components/modals/UnstakeModal.tsx
This gets around some instructions taking share amount args instead of token amounts
An alternative to #31 
```
Withdraw all votes
Burn all votes
Unbond stake worth X tokens
=== New transaction to allow the token owner record to be deleted ===
Mint max votes (Staking program deposits them into governance for you)
```
> Improved unstaking to burn max and then mint max

- app/src/App.less
- app/src/components/Dashboard/StakedJetBalance.tsx
- app/src/components/YourInfo.tsx
- app/src/views/Proposal.tsx
Some styles were missing after upgrading to the latest `jet-antd` package and some style refactoring. This reintroduces the previous styling.
<details>
<summary>
Before
</summary>
</details>
<details>
<summary>
After
</summary>
</details>
> GN-358 Reinstated missing styles

- app/src/components/YourInfo.tsx
Implement share to token conversion so that UI displays number of tokens instead of number of shares.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> GVN-298 Use tokens instead of shares in yourinfo

- programs/staking/src/lib.rs
> staking: export the `PoolConfig` struct from the staking program

- app/src/actions/withdrawUnbonded.ts
- app/src/components/modals/VerifyModal.tsx
- app/src/components/modals/WithdrawModal.tsx
i found it by just setting breakpoints all over the place in chrome DevTools. I didn't see the network request going out, found where that should be happening, and worked backwards.
There's something wrong with either what we're supplying to "withdrawUnbonded" or the instruction setter-upper method itself, but I used withdrawAllUnbonded as I saw that it worked for the other change.
> GVN-363:  Wrong "if" statement caused withdrawal to not be sent, also withdrawAllUnbonded works specifying one account

- app/src/components/modals/VerifyModal.tsx
Make the first step after authenticating a new wallet be the agree to terms modal instead of granting access.
> Agree to terms after auth

- programs/staking/src/events.rs
- programs/staking/src/instructions/cancel_unbond.rs
- tests/airdrop-staking.ts
Canceling unbonds should also readjust the voter weight automatically
> fix voter weight records not being updated in cancel_unbond

- tests/airdrop-staking.ts
They were accidentally commented out in a previous change
> re-enable mass airdrop tests

- app/src/hooks/proposalHooks.ts
Currently, the SPL governance program requires a minimum quorum in order for proposals to pass. This becomes difficult to achieve when there are a large number of voters or token accounts, as the vote weight of each account becomes diluted. In the creation of an SPL governance, we are able to select the percentage needed in order for a proposal to succeed, such as 60%.
However, Jet would like to define a passing proposal as a situation in which the number of cast "approve" votes exceeds the number of cast "deny" votes. Proposals would pass by **simple majority of cast votes**, where the number of accounts that have not voted in either direction are inconsequential to the result of a proposal.
This results in two different methods of defining when a proposal is marked as "passed". Consider …
> Show proposal filter by simple majority

- programs/vote-batcher/src/lib.rs
- tests/vote-batcher.ts
the recently merged governance id changes didn't make it in the recently merged vote-batcher change
> update governance id in vote-batcher

- programs/staking/src/events.rs
- programs/staking/src/instructions/withdraw_unbonded.rs
A minor change to the event log emitted in `withdraw_unbonded_handler`.
> Add unbonding_account to UnbondedWithdrawn

- app/src/views/Proposal.less
- app/src/views/Proposal.tsx
- Show user's vote, if any, as history verbiage below results bars.
- Show "change vote" instead of just "vote" if user already has an existing vote.
This makes it more obvious that the user has already voted on any given proposal.
> GVN-406 Show user vote history more descriptively

- app/src/hooks/proposalHooks.ts
Solana gov program currently gets `voting_completed_at` based on the time when the voting ended and not when we finalized the proposal.
Change our method of displaying proposal end time on the front-end by adding 7 days to proposal start time, instead of getting this value from on-chain.
> Change method of getting deadline from proposal

- app/src/hooks/proposalHooks.ts
Remove frontend workaround to show passed proposals by simple majority
This stops active proposals from erroneously showing up as "passed" before their voting period has completed and been finalised.
> GVN-409 Get proposal result from onchain

- .github/workflows/test.yaml
- Cargo.lock
- package-lock.json
- programs/auth/Cargo.toml
- programs/auth/src/lib.rs
- programs/rewards/Cargo.toml
- programs/rewards/src/instructions/airdrop_close.rs
- programs/rewards/src/lib.rs
- programs/rewards/src/state/distribution.rs
- programs/staking/Cargo.toml
- programs/staking/src/lib.rs
- programs/staking/src/state.rs
- programs/vote-batcher/Cargo.toml
- programs/vote-batcher/src/instructions/relinquish_many.rs
- programs/vote-batcher/src/instructions/vote_many.rs
- programs/vote-batcher/src/lib.rs
- tests/airdrop-staking.ts
- tests/vote-batcher.ts
- creating an auth account is now permissionless (not requiring the target owner of the account to sign in order to create it)
- enforce authority addresses in builds by default, require explicit `testing` feature to opt out
- minor lint updates
> adjust signer/authority requirements
