jet-lab/jet-governance

- app/src/App.less
- app/src/components/modals/RestakeModal.tsx
- app/src/components/modals/StakeModal.tsx
- app/src/components/modals/VerifyModal.tsx
- app/src/components/modals/WithdrawAllModal.tsx
- app/src/components/modals/WithdrawModal.tsx
- app/src/models/GEOBANNED_COUNTRIES.ts
- app/src/routes.tsx
- app/src/utils/utils.ts
<details>
<summary>Click to see the current SMS modal</summary>
</details>
<details>
<summary>Click to see the updated SMS modal</summary>
</details>
> [GVN-220] sms verification modal

- app/package.json
- app/src/App.less
- app/src/components/airdrop/Available.tsx
<details>
<summary>Click to see current mobile button</summary>
</details>
<details>
<summary>Click to see current desktop button</summary>
</details>
<details>
<summary>Click to see updated mobile button</summary>
</details>
<details>
<summary>Click to see updated desktop button</summary>
</details>
> [GVN-343]fix claim button styling

- app/src/actions/voteRecordCsvDownload.ts
- app/src/views/Proposal.tsx
Changing column titles to match
> GVN-347 Changing column titles to match

- app/src/App.less
- app/src/components/modals/VerifyModal.tsx
Jira:
[GVN-340](https://jetprotocol.atlassian.net/browse/GVN-340)
Updates:
- Removed space between checkbox and text, also commas.
- Updated First paragraph and Checkbox paragraph.
- 3 links to the Terms of service, Privacy Policy and Cookie Policy(with a url placeholder for the moment as requested).
Design: 
UX video:
> GVN-340 : Updated legend on Terms modal

- app/src/App.less
- app/src/components/airdrop/Available.tsx
- app/src/components/unbonding/UnbondingLog.tsx
- app/src/constants/math.ts
- app/src/hooks/proposalHooks.ts
- app/src/utils/utils.ts
- app/src/views/FlightLogs.tsx
<details>
<summary>Click to see current unboding log</summary>
</details> 
<details>
<summary>Click to see updated unboding log - unbonding</summary>
</details> 
<details>
<summary>Click to see updated unboding log - unbonded</summary>
</details>
> [GVN-90] Unbonding countdown

- app/src/components/YourInfo.less
- app/src/components/YourInfo.tsx
Jira:
[GVN-349](https://jetprotocol.atlassian.net/browse/GVN-349)
Updates:
- Font size is now changed using calculated with function clamp in CSS.
- When the number is more than 30 characters, the number on newlines is adjusted.
UX video:
Complete UX video [here](https://jetprotocol.atlassian.net/browse/GVN-349?focusedCommentId=10832).
> GVN-349: UI layout bug due to large vote amount

- programs/rewards/src/state/airdrop.rs
<details>
<summary>Click to see current log</summary>
</details>
<details>
<summary>Click to see updated log</summary>
</details>
> update read airdrop tool log

- app/package.json
update jet-antd package from 0.4.21 to 0.4.22
> update jet-antd package

- app/package-lock.json
- app/package.json
- app/src/components/YourInfo.tsx
- app/src/components/modals/WithdrawAllModal.tsx
- app/src/components/unbonding/UnbondingLog.tsx
- app/src/contexts/proposal.tsx
- app/src/utils/utils.ts
- Replaces share to token conversion with `UnbondingAccount.tokens` where appropriate
- Update `jet-engine` version to `0.2.40`
- Remove unused function
> GVN-298 Move share to token conversion to `jet-engine`

- app/src/components/modals/VerifyModal.tsx
<details>
<summary>Click to see current links style</summary>
light:
dark:
</details>
<details>
<summary>Click to see updated links style</summary>
light:
dark:
</details>
> style links

- app/src/components/TermsPrivacy.tsx
- app/src/components/YourInfo.tsx
- app/src/components/docsLink/index.tsx
- app/src/components/modals/UnstakeModal.tsx
- app/src/components/modals/VerifyModal.tsx
- app/src/constants/index.ts
- app/src/constants/labels.ts
Added Rewards Switch for language, removed Cookie Policy for now. and fixed a few things.
> Rewards Language Switch, Cookie Policy, and DocsLink Fix

- app/.env.sample
- app/package-lock.json
- app/package.json
- app/src/components/MobileMessage.tsx
- app/src/components/Navbar.tsx
- app/src/components/YourInfo.tsx
- app/src/components/modals/ClaimModal.tsx
- app/src/components/modals/VerifyModal.tsx
- app/src/contexts/blockExplorer.tsx
- app/src/contexts/connection.tsx
- app/src/utils/utils.ts
- Update Jet Govern to JetGovern across app
- Change VPN block to Origin Restricted
- Loading indicator is disabled after verification
- Troubleshooting wording on access denied modal
> Various UI fixes

- app/src/actions/addStake.ts
- app/src/actions/restake.ts
- app/src/components/modals/ClaimModal.tsx
- app/src/components/modals/RestakeModal.tsx
- app/src/components/modals/StakeModal.tsx
- app/src/components/modals/UnstakeModal.tsx
- app/src/components/modals/VoteModal.tsx
- app/src/components/modals/WithdrawModal.tsx
- app/src/hooks/proposalHooks.ts
- app/src/tools/transactions.tsx
Also cleaned up linting warnings
> Notification grammar

- app/src/components/modals/VerifyModal.tsx
Add link to troubleshooting guide within verification modal.
> Add troubleshooting guide to verification modal

- app/src/components/modals/VerifyModal.tsx
Inform user if unable to detect location from IP address
> Check if unable to get country code

- app/package-lock.json
- app/package.json
- app/src/actions/claimAndStake.ts
- app/src/components/modals/ClaimModal.tsx
add stake account check to airdrop claim
> add check to airdrop claim

- app/src/components/airdrop/Available.tsx
<details>
<summary>Current View</summary>
</details>
<details>
<summary>Updated View</summary>
</details>
> update available component

- app/package-lock.json
- app/package.json
- app/src/actions/voteRecordCsvDownload.ts
- app/src/components/YourInfo.tsx
- app/src/contexts/proposal.tsx
- app/src/hooks/proposalHooks.ts
- app/src/utils/utils.ts
This reverts commit e06dd39f187b0d730c1edbe0ff80617731d4ee90.
> Revert "Fix recompiling causing the app to be unresponsive (#107)"

- app/src/views/Proposal.tsx
Forgot to update the name of the prefix
> fix proposal names

- app/src/components/YourInfo.tsx
Update YourInfo tooltip for more accuracy
> Change YourInfo tooltip

- app/public/index.html
Add Google Tag Manger for marketing analytics
> Google Tag Manager

- app/src/components/TermsPrivacy.tsx
- programs/staking/src/spl_addin.rs
existing docs links are not available for public. updated the links.
> updates docs links
